# Generated by Django 3.2.21 on 2024-02-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciation', '0002_auto_20240224_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='last_correct',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='word',
            name='occur_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
