# Generated by Django 3.2.21 on 2024-02-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciation', '0003_auto_20240225_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='memory_strength',
            field=models.FloatField(default=5),
        ),
    ]
