# Generated by Django 3.2.24 on 2024-02-27 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reciation', '0004_word_memory_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
