# Generated by Django 3.2.24 on 2024-03-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciation', '0005_word_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'managed': False},
        ),
    ]
