# Generated by Django 3.2.24 on 2024-03-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciation', '0006_alter_word_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={},
        ),
    ]
